apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - jaeger/jaeger-deployment.yaml
  - otel-collector-cotrib/otel-collector-deployment.yaml
  - ingress/ingress-config.yaml
  - ingress/ingress-rule.yaml


configMapGenerator:
- name: colector-config
  files:
  - otel-collector-cotrib/config.yaml

generatorOptions:
  disableNameSuffixHash: true

